### ISSUE TITLE
image not showing up in "Sharing economy" story

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/Future_Economy#46]
see attached screenshot (chrome on a mac) - the backend shows the images to be in place. i recall we had this problem with commonplace on the klamath story. if it isn't obvious to you what is goign on might be worth checking with Will as i think he dealt with it in commonplace.
![screen shot 2015-02-02 at 8 27 01 am](https://cloud.githubusercontent.com/assets/4765127/6004136/7837b6f8-aab5-11e4-84fb-dd5b55659be6.png)

**Comment by sarahmagrish** [comment]
another instance if it is helpful...

![screen shot 2015-02-02 at 3 31 22 pm](https://cloud.githubusercontent.com/assets/4765127/6011439/a441eb70-aaf0-11e4-966d-38ca6ce20c3c.png)

**Comment by sarahmagrish** [comment]
yep great - thx

**Comment by ghost** [comment]
Wait - I didn't fix this one yet ^_^

**Comment by sarahmagrish** [comment]
oops wrong issue! ha

**Comment by ghost** [comment]
I'm pretty sure the problem was that there were quotes (") in the Alt tag on the images, and it was screwing up the HTML.  

I added the proper PHP to escape those quotes and it's working now. Please confirm.

**Comment by ghost** [comment]
Okay. In the other instance - it seemed that it wasn't showing because the image had no "Alt" tag.  Make sure to click the edit button on the image, and fill in the Alt Description.

![edit_post_ _future_economy_ _wordpress](https://cloud.githubusercontent.com/assets/886931/6012083/4e78e902-aaf8-11e4-934f-3f53962e8086.png)

![edit_post_ _future_economy_ _wordpress](https://cloud.githubusercontent.com/assets/886931/6012086/6007f50a-aaf8-11e4-8f39-bcf1bdfb2c33.png)

**Comment by sarahmagrish** [comment]
ok! don't leave out alt text (swear i don't do that as a practice - was waiting to go back in on images that lived) and don't use quotation marks in alt text and images should all appear - confirmed this seems to work. closing now unless there is anything else we should note?

**Comment by ghost** [comment]
Well leaving out the Alt description seems strange.  But it appears to be the problem.  The other one, I fixed - so you CAN put quotes in the alt description. But until I can figure out why it’s breaking if they are not there (and again, this is complicated because it’s hidden inside a javascript that loads the images only when you have scrolled to them, so I apologize) just make sure to have alt descriptions.  

—
Jim Krill
jameskrill.com (http://jameskrill.com) | @jimkrill (http://www.twitter.com/jimkrill)

**Comment by sarahmagrish** [comment]
you can just leave that - no worries. alt text is a good practice. now it is mandatory.
