### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by lmilholland** [sarahmagrish/Future_Economy#47]
Hi Jim,

I don't want to sound like a bumpkin, but I'm wondering if you can explain or take a look and see why the site is so slow right now. I want t make some edits in the backend, but it's taking forever for posts to load. My guess is that the reason is because we invited a series of people to go and check it out, and offered them the password. (Which reminds me, can you help us remove the password on Feb. 10?) But does that explain it? Anything else that could be slowing it down? Thank you!

**Comment by ghost** [comment]
If it was the front-end, I'd say yeah I can help you with that - since it might be some code that is slowing it down.  But if it is the backend, that's either the server (Media Temple) or your internet connection.

Having multiple users on at once, editing, shouldn't slow things down (visibly).  You may want to check with Cat or Chris and make sure the hosting package they setup for this project is "powerful" enough to run WordPress... I don't see why it wouldn't be - which makes me wonder if it's just internet connectivity?  

Sorry... that's the best answer I've got ^_^
